apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cardintegration
          labels:
            app: cardintegration
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: cardintegration
          template:
            metadata:
              labels:
                app: cardintegration
            spec:
              containers:
              - name: cardintegration
                image: your-docker-repo/cardintegration:latest
                ports:
                - containerPort: 8080
                env:
                - name: SPRING_PROFILES_ACTIVE
                  value: "prod"