apiVersion: v1
        kind: Service
        metadata:
          name: cardintegration
        spec:
          selector:
            app: cardintegration
          ports:
          - protocol: TCP
            port: 80
            targetPort: 8080
          type: LoadBalancer